### 넘파이 배열 
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결 하고자  
수치 해석 프로그램에서는 numpy라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음

### NumPy import  
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함  
```bash
pip install numpy
```

numpy 패키지를 프로그램에서 사용하려면 import 해야 함

```python
import numpy
import numpyt as np
```

In [177]:
import numpy as np #연결 전에는 노란줄이 뜨게됨



### 1차원 배열 만들기
넘파이의 'array' 함수를 사용하여 리스트를 'ndarray' 타입으로 변경 가능


In [178]:
ndarray_ =np.array([0,1,2,3,4])
ndarray_

array([0, 1, 2, 3, 4])

In [179]:
type(ndarray_)

numpy.ndarray

In [180]:
floats = np.array([1.0,2.0,3.0,4.0])
floats

array([1., 2., 3., 4.])

In [181]:
floats = np.array([0.1,0.2,0.3,0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함
이러한 numpy 배열에 특성 때문에 요소에 대한 접근 속도가 빠름

In [182]:
ndarray_ = np.array([1,1.5,2])
ndarray_

array([1. , 1.5, 2. ])

In [183]:
ndarray_ = np.array(['문자열',1,1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을  
간단한 명령으로 처리할 수 있는 벡터화 연산을 지원함

In [184]:
# 각 요소를 2씩 곱하는 연산 
# 리스트를 사용했을 때
numbers = list(range(10))
result = []
for number in numbers:
    result.append(numbers *2)
result 


[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [185]:
# numpy array를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2* numpy_numbers
result
import numpy as np

array = np.array([1, 2, 3, 4])
result = 2 * array  # 배열의 각 요소에 2를 곱합니다.

print(result)

[2 4 6 8]


In [186]:
result = 2 * numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [187]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5,10)))
numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [188]:
result = (numbers1 * 5) + numbers2    # 넘버스 1 연산후 + 넘버스2
result

array([ 5, 11, 17, 23, 29])

In [189]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [190]:
result = (numbers1 > 2) & (numbers2 <9)
result

numbers1 > 2 , numbers2 < 10 , result


(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True, False]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 'array()' 의 매개변수로
전달하면 2차원 배열을 생성할 수 있음

In [191]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]
          
         ]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
len(numpy_matrix)

3

In [193]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기
리스트의 요소로 2차원형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있음

In [194]:
three_d = [ #리스트 생성
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14 ,15 ,16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d

  
  

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
'ndim()' : 배열의 차원을 정수로 반환
'shape' : 배열의 각 차원의 크기를 정수의 튜플로 반환

In [195]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [196]:
numpy_three_d.ndim, numpy_three_d.shape

(3, (2, 3, 4))

### numpy 배열의 인덱싱
일반적으로 `배열변수 [인덱스]` 의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게   
'배열변수`[인덱스,인덱스,...]`의 형태로 사용함  

- 일반 2차원 리스트 : `리스트[인덱스][인덱스]`  
- numpy 2차원 배열 : `배열[인덱스,인덱스]`

In [197]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [198]:
three_d[1][0][3]   # 16찾는법   2번째줄의 첫번째 에서 3번째


16

In [199]:
numpy_three_d[1,0,3]   #16 접근 법

16

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, '리스트[시작인덱스:종료인덱스]'와 동일함  
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 `,` 를 써야하는 것에 주의


In [200]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [201]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [202]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
numpy_matrix[0,:2]   # 0번 인덱스에서 2개를 잘라서 들고옴

array([1, 2])

In [204]:
numpy_matrix[:2,0]  # 2번 까지 들고온 것에서 0번만 출력함

array([1, 4])

In [205]:
numpy_matrix[1:,1:] # 1번 인덱스부터 끝까지 들고옴

array([[5, 6],
       [8, 9]])

In [206]:
numpy_three_d[:1,:2,:2] # 1번 까지 2번까지 2번까지

array([[[1, 2],
        [5, 6]]])

##### 파이썬으로 다음 연산을 수행한다.
```python
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

```
1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [207]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])


# 1. 이 행렬에서 값 7 을 인덱싱한다.
m[1,2] 
# 2. 이 행렬에서 값 14 을 인덱싱한다.
m[2,4] # m[-1,-1]
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2] 
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[0:2,3:]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
<span style='color: blue;'>**팬시 인덱싱(fancy indexing)**</span> 이라고 부르는 배열 인덱싱 기법이 존재함  
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는 게 아닌  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는  새로운 배열을 반환

### 불리언 배열 인덱싱
`true`, `False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여    
새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야함  

In [213]:
numpy_array = np.array([1,2,3,4,5,6,7,8])
index_array = np.array([True,True,False,False,False,True,True,True])

numpy_array[index_array]






array([1, 2, 6, 7, 8])