### 넘파이 배열 
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결 하고자  
수치 해석 프로그램에서는 numpy라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음

### NumPy import  
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함  
```bash
pip install numpy
```

numpy 패키지를 프로그램에서 사용하려면 import 해야 함

```python
import numpy
import numpyt as np
```

In [1]:
import numpy as np #연결 전에는 노란줄이 뜨게됨

### 1차원 배열 만들기
넘파이의 'array' 함수를 사용하여 리스트를 'ndarray' 타입으로 변경 가능


In [4]:
ndarray_ =np.array([0,1,2,3,4])
ndarray_

array([0, 1, 2, 3, 4])

In [5]:
type(ndarray_)

numpy.ndarray

In [10]:
floats = np.array([1.0,2.0,3.0,4.0])
floats

array([1.2, 2. , 3. , 4. ])

In [12]:
floats = np.array([0.1,0.2,0.3,0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함
이러한 numpy 배열에 특성 때문에 요소에 대한 접근 속도가 빠름

In [14]:
ndarray_ = np.array([1,1.5,2])
ndarray_

array([1. , 1.5, 2. ])

In [15]:
ndarray_ = np.array(['문자열',1,1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을  
간단한 명령으로 처리할 수 있는 벡터화 연산을 지원함

In [17]:
# 일반 리스트를 사용해

TypeError: unsupported operand type(s) for *: 'int' and 'builtin_function_or_method'