### 넘파이 배열 
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결 하고자  
수치 해석 프로그램에서는 numpy라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음

### NumPy import  
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함  
```bash
pip install numpy
```

numpy 패키지를 프로그램에서 사용하려면 import 해야 함

```python
import numpy
import numpyt as np
```

In [370]:
import numpy as np #연결 전에는 노란줄이 뜨게됨



### 1차원 배열 만들기
넘파이의 'array' 함수를 사용하여 리스트를 'ndarray' 타입으로 변경 가능


In [371]:
ndarray_ =np.array([0,1,2,3,4])
ndarray_

array([0, 1, 2, 3, 4])

In [372]:
type(ndarray_)

numpy.ndarray

In [373]:
floats = np.array([1.0,2.0,3.0,4.0])
floats

array([1., 2., 3., 4.])

In [374]:
floats = np.array([0.1,0.2,0.3,0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함
이러한 numpy 배열에 특성 때문에 요소에 대한 접근 속도가 빠름

In [375]:
ndarray_ = np.array([1,1.5,2])
ndarray_

array([1. , 1.5, 2. ])

In [376]:
ndarray_ = np.array(['문자열',1,1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을  
간단한 명령으로 처리할 수 있는 벡터화 연산을 지원함

In [377]:
# 각 요소를 2씩 곱하는 연산 
# 리스트를 사용했을 때
numbers = list(range(10))
result = []
for number in numbers:
    result.append(numbers *2)
result 


[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [378]:
# numpy array를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2* numpy_numbers
result
import numpy as np

array = np.array([1, 2, 3, 4])
result = 2 * array  # 배열의 각 요소에 2를 곱합니다.

print(result)

[2 4 6 8]


In [379]:
result = 2 * numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [380]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5,10)))
numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [381]:
result = (numbers1 * 5) + numbers2    # 넘버스 1 연산후 + 넘버스2
result

array([ 5, 11, 17, 23, 29])

In [382]:
result = numbers1 == 3
result

array([False, False, False,  True, False])

In [383]:
result = (numbers1 > 2) & (numbers2 <9)
result

numbers1 > 2 , numbers2 < 10 , result


(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True, False]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 'array()' 의 매개변수로
전달하면 2차원 배열을 생성할 수 있음

In [384]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]
          
         ]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [385]:
len(numpy_matrix)

3

In [386]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기
리스트의 요소로 2차원형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있음

In [387]:
three_d = [ #리스트 생성
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14 ,15 ,16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d

  
  

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
'ndim()' : 배열의 차원을 정수로 반환
'shape' : 배열의 각 차원의 크기를 정수의 튜플로 반환

In [388]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [389]:
numpy_three_d.ndim, numpy_three_d.shape

(3, (2, 3, 4))

### numpy 배열의 인덱싱
일반적으로 `배열변수 [인덱스]` 의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게   
'배열변수`[인덱스,인덱스,...]`의 형태로 사용함  

- 일반 2차원 리스트 : `리스트[인덱스][인덱스]`  
- numpy 2차원 배열 : `배열[인덱스,인덱스]`

In [390]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [391]:
three_d[1][0][3]   # 16찾는법   2번째줄의 첫번째 에서 3번째


16

In [392]:
numpy_three_d[1,0,3]   #16 접근 법

16

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, '리스트[시작인덱스:종료인덱스]'와 동일함  
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 `,` 를 써야하는 것에 주의


In [393]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [394]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [395]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [396]:
numpy_matrix[0,:2]   # 0번 인덱스에서 2개를 잘라서 들고옴

array([1, 2])

In [397]:
numpy_matrix[:2,0]  # 2번 까지 들고온 것에서 0번만 출력함

array([1, 4])

In [398]:
numpy_matrix[1:,1:] # 1번 인덱스부터 끝까지 들고옴

array([[5, 6],
       [8, 9]])

In [399]:
numpy_three_d[:1,:2,:2] # 1번 까지 2번까지 2번까지

array([[[1, 2],
        [5, 6]]])

##### 파이썬으로 다음 연산을 수행한다.
```python
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

```
1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [400]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])


# 1. 이 행렬에서 값 7 을 인덱싱한다.
m[1,2] 
# 2. 이 행렬에서 값 14 을 인덱싱한다.
m[2,4] # m[-1,-1]
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2] 
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[0:2,3:]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
<span style='color: blue;'>**팬시 인덱싱(fancy indexing)**</span> 이라고 부르는 배열 인덱싱 기법이 존재함  
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는 게 아닌  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는  새로운 배열을 반환

### 불리언 배열 인덱싱
`true`, `False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여    
새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야함  

In [401]:
numpy_array = np.array([1,2,3,4,5,6,7,8])
index_array = np.array([True,True,False,False,False,True,True,True])

numpy_array[index_array]

array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [402]:
numpy_array % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [403]:
numpy_array % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [404]:
numpy_array [numpy_array % 2 == 0]

array([2, 4, 6, 8])

#### 정수 배열 인덱싱
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된 배열을 인덱스로  
전달하여 해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [405]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [406]:
index_array = np.array([0,2,3])
index_array

array([0, 2, 3])

In [407]:
numpy_array[index_array]

array([1, 3, 4])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨

인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우
에외가 발생함

In [408]:
index_array = np.array([0,2,3,4,5,1,6,2,5])

In [409]:
numpy_array[index_array]

array([1, 3, 4, 5, 6, 2, 7, 3, 6])

In [410]:
index_array = np.array([0,2,3,4,5,1,6,2,5,20])

In [411]:
numpy_array[index_array] #인덱스 범위를 초과하는 20의 수를 넣었더니 에러가 뜸

IndexError: index 20 is out of bounds for axis 0 with size 8

#### 다차원 배열에서 배열 인덱싱

In [412]:
index_array = np.array([True,False,True])
numpy_matrix[:2, index_array]

array([[1, 3],
       [4, 6]])

In [413]:
#배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경 됨
numpy_matrix[[2,1,0],:]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])


#### 파이썬으로 다음 연산을 수행한다
다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [414]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


x[x %3 ==0]
x[x %4 ==1]
x[(x%3==0)&(x %4==1)]


array([9])

### numpy 배열의 자료형
numpy 배열의 원소는 모두 같은 데이터 타입을 가지고 있음  
numpy 배열의 데이터 타입을 확인하고자 한다면 `dtype` 속성으로 확인이 가능함

In [415]:
numpy_array = np.array([1,2,3])   # 재정의
numpy_array.dtype

dtype('int32')

In [416]:
numpy_array = np.array([1.0,2.0,3.0])
numpy_array.dtype

dtype('float64')

In [417]:
numpy_array = np.array(['1.0','2.0','3.0'])  
numpy_array.dtype

dtype('<U3')

'array()' 함수를 사용하여 배열을 생성할 때   
명시적으로 데이터 타입을 지정하지 않으면 자동으로 데이터 타입을 추론하여 지정하게 됨    
만약 명시적으로 데이터 타입을 지정하고자 한다면  
`array()` 함수에 `dtype` 매개변수로 데이터 타입을 지정해 주면 됨  

##### dtype의 접두사
b: 불리언  　  i: 정수  　  f: 실수 　   U: 유니코드

In [418]:
numpy_array = np.array(['1.0','2.0','3.0'],dtype='f')   #뒤쪽에 dtype으로 타입 지정 가능 
numpy_array.dtype

dtype('float32')

In [419]:
numpy_array # 실수 형태로 변해있음

array([1., 2., 3.], dtype=float32)

### numpy에서 inf와 NaN
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `-inf`, 0을 0으로 나누면 `nan`이 반환됨

### 배열 생성
numpy 배열을 생성하는 방법
- `zeros`, `ones`
- `zeros_like`, `ones_like`
- `empty`
- `arange`
- `linspace`, `logspace` 

#### zeros
크기가 정해져 있고 원소를 0으로 초기화한 배열을 생성하는 함수

In [420]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [421]:
# 매개변수로 정수 튜플을 전달하여 다차원 배열 생성도 가능
numpy_array = np.zeros((2,3)) #2 행 3열의 이차원 배열 생성
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [422]:
# dtype을 명시하여 데이터 타입을 지정할 수 있음
numpy_array = np.zeros((2,3),dtype='i')  # 실수형 이었으나 정수형으로 변경 가능
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약 dtype으로 문자열 (U) 형태로 지정하게 되면 문자열의 길이가 초과된 부분이 손실됨

#### ones 
크기가 정해져 있고 원소를 1로 초기화한 배열을 생성하는 함수
`zeros` 함수와 사용법이 동일

In [423]:
ones_array = np.ones((3,2,2),dtype='i')    #3개 2개 2개에 정수형 타입
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0 또는 1로 채워진 배열을 생성하는 함수

In [424]:
zeros_array = np.zeros_like(ones_array,dtype='i')     # zeros_like에 ones_array를 전달
zeros_array

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

#### empty
크기만 지정하고 원소의 값은 '쓰레기 데이터'로 채워진 배열을 생성 
`zeros`, `ones` 함수를 사용하여 배열을 생성하는 것보다 배열 생성 속도가 빠름

In [425]:
empty_array = np.empty((10,10))  #괄호를 하나 더 치면 사이즈를 지정할 수 있음
empty_array

array([[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        6.95301293e-310, 4.69362364e-322, 1.44401424e-311,
        1.44401635e-311, 1.44401425e-311, 1.44401425e-311,
        1.44401424e-311],
       [1.44401425e-311, 1.44401635e-311, 1.44401425e-311,
        1.44401425e-311, 1.44401424e-311, 1.44401425e-311,
        1.44401425e-311, 1.44401635e-311, 1.44401425e-311,
        1.44401424e-311],
       [1.44401425e-311, 1.44401425e-311, 1.44401424e-311,
        1.44401424e-311, 1.44401635e-311, 1.44401424e-311,
        1.44401424e-311, 1.44401425e-311, 1.44401425e-311,
        1.44401424e-311],
       [1.44401425e-311, 1.44401424e-311, 1.44401635e-311,
        1.44401424e-311, 1.44401424e-311, 1.44401425e-311,
        1.44401635e-311, 1.44401425e-311, 1.44401425e-311,
        1.44401425e-311],
       [1.44401425e-311, 1.44401425e-311, 1.44401424e-311,
        1.44401424e-311, 1.44401425e-311, 1.44401425e-311,
        1.44401425e-311, 1.44401425e-311, 1.44401425e-311,
        1.4

#### arange
파이썬의 내장함수 `range()` 함수와 동일한 기능을 하는 numpy 배열 생성 함수

In [426]:
arange_array = np.arange(10,50) 
arange_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [427]:
arange_array = np.arange(50,10,-1) 
arange_array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11])

### 전치 연산
배열의 행과 열의 위치를 전치시키는 방법 배열의 `T`속성으로 반환 받을 수 있음

In [428]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [429]:
numpy_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [430]:
numpy_three_d.T   # 2, 3, 4 -> 4, 3, 2

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])