### 넘파이 배열 
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결 하고자  
수치 해석 프로그램에서는 numpy라고 하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음

### NumPy import  
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함  
```bash
pip install numpy
```

numpy 패키지를 프로그램에서 사용하려면 import 해야 함

```python
import numpy
import numpyt as np
```

In [3]:
import numpy as np #연결 전에는 노란줄이 뜨게됨



### 1차원 배열 만들기
넘파이의 'array' 함수를 사용하여 리스트를 'ndarray' 타입으로 변경 가능


In [ ]:
ndarray_ =np.array([0,1,2,3,4])
ndarray_

In [ ]:
type(ndarray_)

In [ ]:
floats = np.array([1.0,2.0,3.0,4.0])
floats

In [ ]:
floats = np.array([0.1,0.2,0.3,0.4])
floats

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함
이러한 numpy 배열에 특성 때문에 요소에 대한 접근 속도가 빠름

In [ ]:
ndarray_ = np.array([1,1.5,2])
ndarray_

In [ ]:
ndarray_ = np.array(['문자열',1,1.5])
ndarray_

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을  
간단한 명령으로 처리할 수 있는 벡터화 연산을 지원함

In [ ]:
# 각 요소를 2씩 곱하는 연산 
# 리스트를 사용했을 때
numbers = list(range(10))
result = []
for number in numbers:
    result.append(numbers *2)
result 


In [ ]:
# numpy array를 사용했을 때
numpy_numbers = np.array(numbers)
result = 2* numpy_numbers
result
import numpy as np

array = np.array([1, 2, 3, 4])
result = 2 * array  # 배열의 각 요소에 2를 곱합니다.

print(result)

In [ ]:
result = 2 * numbers
result

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능

In [ ]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5,10)))
numbers1, numbers2

In [ ]:
result = (numbers1 * 5) + numbers2    # 넘버스 1 연산후 + 넘버스2
result

In [ ]:
result = numbers1 == 3
result

In [ ]:
result = (numbers1 > 2) & (numbers2 <9)
result

numbers1 > 2 , numbers2 < 10 , result


### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 'array()' 의 매개변수로
전달하면 2차원 배열을 생성할 수 있음

In [ ]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]
          
         ]
numpy_matrix = np.array(matrix)
numpy_matrix

In [ ]:
len(numpy_matrix)

In [ ]:
len(numpy_matrix[0])

### 3차원 배열 만들기
리스트의 요소로 2차원형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있음

In [ ]:
three_d = [ #리스트 생성
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14 ,15 ,16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]
numpy_three_d = np.array(three_d)
numpy_three_d

  
  

### 배열의 차원과 크기 구하기
'ndim()' : 배열의 차원을 정수로 반환
'shape' : 배열의 각 차원의 크기를 정수의 튜플로 반환

In [ ]:
numpy_matrix.ndim, numpy_matrix.shape

In [ ]:
numpy_three_d.ndim, numpy_three_d.shape

### numpy 배열의 인덱싱
일반적으로 `배열변수 [인덱스]` 의 형태로 사용함  
다차원 형태일 경우는 일반 리스트와 다르게   
'배열변수`[인덱스,인덱스,...]`의 형태로 사용함  

- 일반 2차원 리스트 : `리스트[인덱스][인덱스]`  
- numpy 2차원 배열 : `배열[인덱스,인덱스]`

In [ ]:
# 일반 3차원 리스트
three_d

In [ ]:
three_d[1][0][3]   # 16찾는법   2번째줄의 첫번째 에서 3번째


In [ ]:
numpy_three_d[1,0,3]   #16 접근 법

### numpy 배열 슬라이싱
일반 리스트에서 사용하는 배열 슬라이싱 방법, '리스트[시작인덱스:종료인덱스]'와 동일함  
단, 다차원 배열일 경우 인덱스를 여러개 지정할 때 `,` 를 써야하는 것에 주의


In [ ]:
numpy_matrix

In [ ]:
numpy_matrix[:]

In [ ]:
numpy_matrix[:2]

In [ ]:
numpy_matrix[0,:2]   # 0번 인덱스에서 2개를 잘라서 들고옴

In [ ]:
numpy_matrix[:2,0]  # 2번 까지 들고온 것에서 0번만 출력함

In [ ]:
numpy_matrix[1:,1:] # 1번 인덱스부터 끝까지 들고옴

In [ ]:
numpy_three_d[:1,:2,:2] # 1번 까지 2번까지 2번까지

##### 파이썬으로 다음 연산을 수행한다.
```python
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

```
1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [ ]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])


# 1. 이 행렬에서 값 7 을 인덱싱한다.
m[1,2] 
# 2. 이 행렬에서 값 14 을 인덱싱한다.
m[2,4] # m[-1,-1]
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1,1:3]
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:,2] 
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[0:2,3:]

### 배열 인덱싱
<span style='color: blue;'>**팬시 인덱싱(fancy indexing)**</span> 이라고 부르는 배열 인덱싱 기법이 존재함  
이 배열 인덱싱은 인덱스로 정수 형태나 슬라이스 형태로 인덱스를 전달하는 게 아닌  
인덱스로 또 다른 넘파이 배열을 전달하여 그에 부합하는  새로운 배열을 반환

### 불리언 배열 인덱싱
`true`, `False` 두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여    
새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기존 배열과 인덱스로 전달하는 배열의 크기가 같아야함  

In [ ]:
numpy_array = np.array([1,2,3,4,5,6,7,8])
index_array = np.array([True,True,False,False,False,True,True,True])

numpy_array[index_array]

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [ ]:
numpy_array % 2

In [ ]:
numpy_array % 2 == 0

In [ ]:
numpy_array [numpy_array % 2 == 0]

#### 정수 배열 인덱싱
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소의 인덱스를 가리키는 정수로 구성된 배열을 인덱스로  
전달하여 해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [ ]:
numpy_array

In [ ]:
index_array = np.array([0,2,3])
index_array

In [ ]:
numpy_array[index_array]

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용 가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨

인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우
에외가 발생함

In [ ]:
index_array = np.array([0,2,3,4,5,1,6,2,5])

In [ ]:
numpy_array[index_array]

In [ ]:
index_array = np.array([0,2,3,4,5,1,6,2,5,20])

In [ ]:
numpy_array[index_array] #인덱스 범위를 초과하는 20의 수를 넣었더니 에러가 뜸

#### 다차원 배열에서 배열 인덱싱

In [ ]:
index_array = np.array([True,False,True])
numpy_matrix[:2, index_array]

In [ ]:
#배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경 됨
numpy_matrix[[2,1,0],:]


#### 파이썬으로 다음 연산을 수행한다
다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


x[x %3 ==0]
x[x %4 ==1]
x[(x%3==0)&(x %4==1)]


### numpy 배열의 자료형
numpy 배열의 원소는 모두 같은 데이터 타입을 가지고 있음  
numpy 배열의 데이터 타입을 확인하고자 한다면 `dtype` 속성으로 확인이 가능함

In [ ]:
numpy_array = np.array([1,2,3])   # 재정의
numpy_array.dtype

In [ ]:
numpy_array = np.array([1.0,2.0,3.0])
numpy_array.dtype

In [ ]:
numpy_array = np.array(['1.0','2.0','3.0'])  
numpy_array.dtype

'array()' 함수를 사용하여 배열을 생성할 때   
명시적으로 데이터 타입을 지정하지 않으면 자동으로 데이터 타입을 추론하여 지정하게 됨    
만약 명시적으로 데이터 타입을 지정하고자 한다면  
`array()` 함수에 `dtype` 매개변수로 데이터 타입을 지정해 주면 됨  

##### dtype의 접두사
b: 불리언  　  i: 정수  　  f: 실수 　   U: 유니코드

In [ ]:
numpy_array = np.array(['1.0','2.0','3.0'],dtype='f')   #뒤쪽에 dtype으로 타입 지정 가능 
numpy_array.dtype

In [ ]:
numpy_array # 실수 형태로 변해있음

### numpy에서 inf와 NaN
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `-inf`, 0을 0으로 나누면 `nan`이 반환됨

### 배열 생성
numpy 배열을 생성하는 방법
- `zeros`, `ones`
- `zeros_like`, `ones_like`
- `empty`
- `arange`
- `linspace`, `logspace` 

#### zeros
크기가 정해져 있고 원소를 0으로 초기화한 배열을 생성하는 함수

In [ ]:
numpy_array = np.zeros(5)
numpy_array

In [ ]:
# 매개변수로 정수 튜플을 전달하여 다차원 배열 생성도 가능
numpy_array = np.zeros((2,3)) #2 행 3열의 이차원 배열 생성
numpy_array

In [ ]:
# dtype을 명시하여 데이터 타입을 지정할 수 있음
numpy_array = np.zeros((2,3),dtype='i')  # 실수형 이었으나 정수형으로 변경 가능
numpy_array

만약 dtype으로 문자열 (U) 형태로 지정하게 되면 문자열의 길이가 초과된 부분이 손실됨

#### ones 
크기가 정해져 있고 원소를 1로 초기화한 배열을 생성하는 함수
`zeros` 함수와 사용법이 동일

In [ ]:
ones_array = np.ones((3,2,2),dtype='i')    #3개 2개 2개에 정수형 타입
ones_array

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0 또는 1로 채워진 배열을 생성하는 함수

In [ ]:
zeros_array = np.zeros_like(ones_array,dtype='i')     # zeros_like에 ones_array를 전달
zeros_array

#### empty
크기만 지정하고 원소의 값은 '쓰레기 데이터'로 채워진 배열을 생성 
`zeros`, `ones` 함수를 사용하여 배열을 생성하는 것보다 배열 생성 속도가 빠름

In [ ]:
empty_array = np.empty((10,10))  #괄호를 하나 더 치면 사이즈를 지정할 수 있음
empty_array

#### arange
파이썬의 내장함수 `range()` 함수와 동일한 기능을 하는 numpy 배열 생성 함수

In [ ]:
arange_array = np.arange(10,50) 
arange_array

In [ ]:
arange_array = np.arange(50,10,-1) 
arange_array

### 전치 연산
배열의 행과 열의 위치를 전치시키는 방법 배열의 `T`속성으로 반환 받을 수 있음

In [ ]:
numpy_matrix

In [ ]:
numpy_matrix.T

In [ ]:
numpy_three_d.T   # 2, 3, 4 -> 4, 3, 2

### 배열의 크기 변경
numpy 배열에서 원소의 개수를 유지한 상태로 배열의 형태를 변경하려 한다면
`reshape` 메서드를 사용하여 변경할 수 있음

In [ ]:
numpy_array = np.zeros(12)
numpy_array

In [ ]:
reshape_array = numpy_array.reshape(2,6)
reshape_array


numpy 배열의 원소는 개수가 정해져 있기 때문에 `reshape` 메서드안에   
하나의 인자로 -1을 넣게 되면 다른 인자들을 통해서 추론하여 지정

In [ ]:
reshape_array = numpy_array.reshape(6,-1)
reshape_array

In [ ]:
reshape_array = numpy_array.reshape(2,2,-1)
reshape_array

만약 , `reshape` 메서드의 인자들의 곱의 결과가 기존 배열의 원소의 총 합과 다르면 에러가 발생  
-1로 지정한 인자가 있을 때 해당 인자의 곱으로 총합을 계산할 수 없는 경우면 에러가 발생

In [ ]:
reshape_array = numpy_array.reshape(5,2)
reshape_array

In [ ]:
reshape_array = numpy_array.reshape(5,-1)
reshape_array

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten` 이나 `ravel` 메서드를 사용

In [ ]:
numpy_matrix = np.empty((3,4))
numpy_matrix

In [ ]:
numpy_array = numpy_matrix.flatten()
numpy_array

In [ ]:
numpy_array = numpy_matrix.ravel()
numpy_array

배열 사용해서 주의할 점은 *길이가 5인 1차원 배열* 과 *길이가 5x1인 2차원 배열*, *1 x5인 2차원  배열* 은   
서로 각각 다른 배열 (요소의 개수와 내용, 순서가 모두 같더라도 형태가 다르면 다른 배열)

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis` 속성으로 차원을 증가 시킬 수 있음

In [ ]:
newaxis_array = numpy_array[:, np.newaxis]    # 1차원 배열의 상태에서 차원 증가
newaxis_array

### 배열 연결하기
행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법
- `hstack` : 행의 수가 같은 두 개 이상의 배열을 연결
- `vstack` : 열의 수가 같은 두 개 이상의 배열을 연결
- `dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결
- `stack`  : dstack 확장 기능으로 행과 열의 수가 같은 두 개이상의 배열을 연결 단,축을 개발자가 직접 지정  
- `r_` : 배열의 요소를 연결, 메서드 인자를 `[]`에 전달함
- `c_` : 행끼리 연결, 최소 2차원의 배열로 연결
- `tile` : 하나의 배열을 여러번 반복하여 연결

In [ ]:
zeros_array = np.zeros((3,4))
zeros_array


In [ ]:
ones_array = np.ones((3,2))
ones_array

In [ ]:
hstack_array = np.hstack([zeros_array,ones_array])
hstack_array

In [ ]:
zeros_array = np.zeros((3,4))
ones_array = np.ones((2,4))

In [ ]:
vstack_array = np.vstack((ones_array,zeros_array))
vstack_array

In [ ]:
zeros_array = np.zeros((3,3))
ones_array = np.ones((3,3))
dstack_array = np.dstack((zeros_array,ones_array))





In [ ]:
zeros_array = np.zeros((3, 4))
ones_array = np.ones((3, 4))  

In [ ]:
stack_array = np.stack([zeros_array, ones_array])
stack_array

In [ ]:
stack_array = np.stack([zeros_array, ones_array], axis=1)
stack_array

In [ ]:
r_array = np.r_[zeros_array, ones_array]
r_array

In [ ]:
c_array = np.c_[zeros_array, ones_array]
c_array

In [ ]:
tile_array = np.tile(zeros_array,2)
tile_array

In [ ]:
tile_array = np.tile(zeros_array,(3,2))
tile_array

##### 파이썬으로 다음 연산을 수행한다.
### 배열 연결하기

행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법
- `hstack` : 행의 수가 같은 두 개 이상의 배열을 연결
- `vstack` : 열의 수가 같은 두 개 이상의 배열을 연결
- `dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결
- `stack`  : dstack 확장 기능으로 행과 열의 수가 같은 두 개이상의 배열을 연결 단,축을 개발자가 직접 지정  
- `r_` : 배열의 요소를 연결, 메서드 인자를 `[]`에 전달함
- `c_` : 행끼리 연결, 최소 2차원의 배열로 연결
- `tile` : 하나의 배열을 여러번 반복하여 연결

지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])

In [ ]:
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 2))  
hstack_array = np.hstack([zeros_array,ones_array])
hstack_array

arange_array = np.arange (10,151,10)
reshape_array = arange_array.reshape(3,5)
reshape_array

vstack_array = np.vstack([hstack_array,reshape_array])
vstack_array

tile_array = np.tile(vstack_array,(2,1))
tile_array


### 2차원 그리드 포인트 생성

좌표값의 쌍(그리드 포인트)을 생성하는 메서드 `meshgrid` 함수로  
x축과 y축의 점들로 사각형의 영역을 나타내는 조합을 생성

In [ ]:
x= np.arange(3)
x


In [ ]:
y= np.arange(5)
y

In [ ]:
X , Y = np.meshgrid(x,y)
X,Y

In [ ]:
[list(zip(x,y)) for x,y in zip(X,Y)]


### 벡터화 연산 

numpy 배열은 반복문을 쓰지 않고 배열에 대하여 벡터 연산을 할 수 있음

In [ ]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [ ]:
%%time
z = np.zeros_like(x)
for index in range(len(x)):
    z[index] = x[index] + y[index]



In [ ]:
%%time
z=x+y

In [ ]:
x= np.arange(5)
y= np.arange(10,15)
z= np.arange(5)


In [ ]:
np.all(x==y)

In [ ]:
np.all(y==z)

In [ ]:
np.all(x <=y )

In [ ]:
array = np.array([0,10,20,30,40])
array


In [ ]:
x*100 

In [ ]:
100 *x 

### 브로드 캐스팅

차원이 서로 다른 배열을 연산하는 기능  
 부족한 차원에 대하여 반복 확장하여 큰 배열의 크기에 맞춘 후 연산을 진행한다

In [ ]:
x = np.arange(5)
x

In [ ]:
x +1


In [ ]:
# 2차원으로 만들기
x = np.arange(15)
x = x.reshape(3,5)     

In [ ]:
y = np.arange(5)
y

In [ ]:
x+y

In [ ]:
y= np.arange(3)
y= y.reshape(3,1)
x+y

### 차원 축소 연산

배열의 하나의 행을 하나의 집합으로 보고  
그 집합에 대한 집계 처리 결과로 새로운 값을 반환하여 배열을 생성

In [ ]:
x = np.arange(10)
x = x.reshape(2,5)


In [ ]:
x.max()

In [ ]:
x.min()

In [ ]:
x.sum()

In [ ]:
x.mean()

In [ ]:
x.sum(axis=0)

In [ ]:
x.sum(axis=0)

In [ ]:
x.sum(axis=1)

### 정렬
`sort` 메서드로 배열을 정렬 할 수 있음  
`axis` 매개변수로 정렬 기준을 정할 수 있음  
`axis=0` : 행을 따로 분리하여 정렬  
`axis=1` : 열을 따로 분리하여 정렬  
`axis`를 지정하지 않으면 가장 나중 차원을 기준으로 정렬  

In [267]:
# [5,2,7,4],
# [11,8,6,4],
# [8,5,11,2]
x = np.array([
    [5, 2, 7, 4],
    [11, 8, 6, 4],
    [8, 5, 11, 2]
])
x

array([[ 5,  2,  7,  4],
       [11,  8,  6,  4],
       [ 8,  5, 11,  2]])

In [270]:
x.sort()
x

array([[ 2,  2,  5,  6],
       [ 4,  5,  7,  8],
       [ 4,  8, 11, 11]])

In [268]:
x.sort(axis=0)
x

array([[ 5,  2,  6,  2],
       [ 8,  5,  7,  4],
       [11,  8, 11,  4]])

In [269]:
x.sort(axis=1)
x

array([[ 2,  2,  5,  6],
       [ 4,  5,  7,  8],
       [ 4,  8, 11, 11]])

In [271]:
np.argsort(x)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [272]:
np.argsort(x, axis = 0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]], dtype=int64)

#### **넘파이로 다음 연산을 수행한다.**

실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

[5,11,12,]
[0,18,22]
[8,2,7]

In [293]:
x = np.array([
    [5, 11, 12],
    [0, 18, 22],
    [8, 2, 7]
])
x

array([[ 5, 11, 12],
       [ 0, 18, 22],
       [ 8,  2,  7]])

In [276]:
#1. 전체의 최댓값
x.max()

22

In [289]:
#2. 각 행의 합
x.sum(1)


x.sum(axis=1)

array([28, 40, 17])

In [290]:
#3. 각 행의 최댓값
x.max(1)
x.max(axis=1)

array([12, 22,  8])

In [295]:
#4. 각 열의 평균
x.mean(axis=0)

array([ 4.33333333, 10.33333333, 13.66666667])

In [294]:
#5. 각 열의 최솟값
x.min(axis=0)

array([0, 2, 7])

### Numpy 배열 통계 연산

- 데이터 개수 구하기 : `len()` 내장 함수
- 표본 평균 : `mean()` 메서드
- 표본 분산 : `var()` 메서드
- 표본 표준편차 : `std()` 메서드
- 최대,최소 : `max()`,`min()` 메서드
- 중앙값 : `median()` 메서드
- 사분위수 `percentile()` 메서드

In [4]:
samples = np.array([9,2,4,20,24,2,23,92,24,-23])
samples

In [12]:
sample_volume =len(samples)
sample_volume

10

In [16]:
sample_mean = samples.mean()        #표현 1
sample_mean
sample_mean = np.mean(samples)      #표현 2
sample_mean

17.7

In [15]:
sample_variance = samples.var()     #표현 1
sample_variance


804.61

In [ ]:
sample_vairance = np.var(samples)   #표현 2
sample_variance


In [22]:
sample_standard = samples.std()     #표현 1
sample_standard


28.365648238670662

In [24]:
sample_standard = np.std(samples)   #표현 2
sample_standard

28.365648238670662

In [28]:
sample_max = samples.max()
sample_max

92

In [27]:
sample_min = samples.min()
sample_min

-23

In [33]:
sample_median = np.median(samples)
sample_median

14.5

In [37]:
sample_0per = np.percentile(samples,0) # 최소값
sample_0per

-23.0

In [38]:
sample_25per = np.percentile(samples,25)
sample_25per

2.5

In [39]:
sample_50per = np.percentile(samples,50)
sample_50per

14.5

In [41]:
sample_75per = np.percentile(samples,75)
sample_75per

23.75

In [42]:
sample_100per = np.percentile(samples,100)
sample_100per

92.0

### 난수 생성에 필요한 시드 설정
numpy 패키지에 있는 `seed()` 메서드에 매개변수로 난수 생성시 필요한 시드를 설정 함

In [51]:
np.random.seed(10)

In [52]:
random_array = np.random.rand(10)
random_array

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

### 데이터 순서를 임의로 바꾸기
numpy 패키지의 random 하위 패키지의 `shuffle()` 메서드로 배열을 임의 순서로 변경 가능 (자체 변환)


In [54]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.random.shuffle(range_array)
range_array


array([8, 1, 6, 4, 5, 0, 7, 3, 9, 2])

### 데이터 샘플링
모집단 배열에 표본으로 사용할 표본 집단 배열을 무작위로 선택하는  방법  
numpy 패키지의 random 하위패키지의   
'choice(모집단배열,표본크기,중복선택여부,각요소의 선택확률)`  
메서드로 사용 가능

In [61]:
population_array = np.arange(10)
population_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# 시드를 설정하면 랜덤수가 나오긴 하지만 매번 시드 설정시 같은 수가 나옴
sample_array = np.random.choice(population_array,5) 
sample_array

array([9, 2, 0, 6, 7])

In [70]:
# 중복값을 허용하지 않은 수들
sample_array = np.random.choice(population_array,5,replace=False) 
sample_array

array([9, 4, 6, 7, 0])

In [96]:
# 확률 (3안나옴)
probability_array = [0.1,0.05,0.05,0,0.15,0.25,0.1,0.05,0.05,0.2]
sample_array = np.random.choice(population_array,5,replace=False,p=probability_array) 
sample_array

array([0, 9, 5, 7, 8])

In [97]:
# 확률
probability_array = [0.1,0.05,0.05,0,0.15,0.25,0.1,0.05,0.05,0.2]
sample_array = np.random.choice(population_array,10000,p=probability_array) 
sample_array

array([8, 4, 4, ..., 9, 9, 5])

In [83]:
# probability_array 의 1이 크거나 작거나 ,probability_array  크기가 하나 더 많거나 적거나
probability_array = [0.1,0.05,0.05,0,0.15,0.25,0.1,0.05,0.05,0.2]
sample_array = np.random.choice(population_array,10000,p=probability_array) 
sample_array

array([4, 8, 5, ..., 4, 6, 9])

### 난수 배열 생성
- `rand()`: 0과 1사이의 균일 분포를 따르는 난수 배열 생성  
- `randn()`: 표준 정규 분포를 따르는 난수 배열 생성  
- `randint(low,high = 정수, size = 정수 혹은 튜플)`: 지정한 범위 정수의 균일 분포를 따르는 배열 생성

※ 균일 분포 = 1~10가지의 수중에 1의 확률은 0.1
※ 정규 분포 = 1~10 에서 5.5 표준 5.5일수록 높은 확률 5.5와 멀어질수록 확률 낮아짐
(대중적으로 정규 분포를 사용)
                                                     

In [87]:
rand_array = np.random.rand(10)
rand_array

array([0.22410849, 0.50771886, 0.55580022, 0.4108698 , 0.5259888 ,
       0.10304517, 0.99308402, 0.71236272, 0.57406141, 0.14801234])

In [89]:
randn_array = np.random.randn(10)
randn_array

array([ 0.37352311, -0.79647895,  1.74471276,  1.92714071, -0.33211564,
        0.09973547,  1.45868107, -0.37504158,  0.31857713, -0.89936769])

In [90]:
randint_array = np.random.randint(10)
randint_array

2

In [91]:
randint_array = np.random.randint(10, size=10)
randint_array

array([3, 0, 3, 9, 2, 1, 6, 5, 6, 2])

In [93]:
randint_array = np.random.randint(10, size=10 ,high=20 )
randint_array

array([16, 10, 13, 10, 16, 14, 19, 11, 17, 13])

In [95]:
randint_array = np.random.randint(10, size=(3,5) ,high=20 )
randint_array

array([[11, 10, 12, 11, 12],
       [13, 13, 11, 10, 12],
       [10, 17, 15, 18, 15]])

### 정수 데이터 카운팅
배열의 요소가 정수이면 `unique()` 메서드나 `bincount()` 메서드로 간단하게 분석할 수 있음

In [99]:
analysys_array = np.unique(sample_array)
analysys_array

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [101]:
analysys_array = np.unique(sample_array,return_counts=True)
analysys_array

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]),
 array([1018,  502,  480, 1527, 2473,  996,  496,  484, 2024], dtype=int64))

In [102]:
analysys_array = np.bincount(sample_array,minlength=10)
analysys_array

array([1018,  502,  480,    0, 1527, 2473,  996,  496,  484, 2024],
      dtype=int64)